title: 'Vipin Kumar M'
email: Vipin.Madhaan@gmail.com
timezone: 'Asia/Kolkata'
baseurl: ''
permalink: '/:title'
logo: 'assets/images/icons/logo.png'
favicon: 'assets/images/icons/favicon.ico'
author: Vipin Kumar M
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: 'compressed'
ganalytics: GTM-TS9R24Q
jekyll-minifier:
  exclude: 'sitemap.xml'

# Authors
authors:
  VipinMadhaan:
    name: Vipin Kumar M
    display_name: Vipin Kumar M
    avatar: 'assets/images/icons/vipin.png'
    email: Vipin.Madhaan@gmail.com
    web: https://www.imadhaan.com
    twitter: https://twitter.com/VipinMadhaan
    description: 'I am a passionate full stack developer from India. I write about web development technologies and learn how to become a better developer.'

# Social
social:
  twitter: https://twitter.com/VipinMadhaan
  linkedin: https://linkedin.com/in/VipinMadhaan
  github: https://github.com/VipinMadhaan

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-minifier
