title: 'portfolio'
email: Vipin.Madhaan@gmail.com
timezone: 'Asia/Kolkata'
baseurl: '/'
permalink: '/:title'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Vipin Kumar M
paginate: 30
disqus: 'VipinMadhaan'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: 'compressed'
ganalytics: UA-113961478-1

# Authors
authors:
  john:
    name: Vipin Kumar M
    display_name: Vipin Kumar M
    avatar: 'assets/images/john.png'
    email: Vipin.Madhaan@gmail.com
    web: https://www.imadhaan.com
    twitter: https://twitter.com/VipinMadhaan
    description: 'This is the author box. Write a short description of the author here.'

# Social
social:
  twitter: https://twitter.com/VipinMadhaan
  linkedin: https://linkedin.com/VipinMadhaan
  github: https://github.com/VipinMadhaan

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
